#!/bin/bash

# Build script for Black Atom Obsidian theme

echo "🔨 Building Black Atom Obsidian theme..."

# Step 1: Generate theme tokens from templates using Black Atom Core
echo "📦 Generating theme tokens..."
black-atom-core adapt

# Step 2: Create a combined CSS file with theme tokens and styling
echo "🎨 Compiling theme..."

# First, create a temporary file with theme tokens content
TOKEN_CONTENT=$(cat templates/theme-tokens.css)

# Then compile the SCSS file to a temporary location
npx sass src/scss/main.scss:/tmp/black-atom-style.css --style compressed

# Now combine them into the final theme.css
echo "/* Black Atom Theme for Obsidian */" > theme.css
echo "/* Generated by Black Atom Core */" >> theme.css
echo "" >> theme.css
echo "$TOKEN_CONTENT" >> theme.css
echo "" >> theme.css
cat /tmp/black-atom-style.css >> theme.css
rm -f /tmp/black-atom-style.css

echo "✅ Build complete!"